//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerSwitcher.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerSwitcher.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://github.com/Petrroll/PowerSwitcher 的本地化字符串。
        /// </summary>
        internal static string AboutAppURL {
            get {
                return ResourceManager.GetString("AboutAppURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电源模式切换 的本地化字符串。
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电源状态改变时自动切换 的本地化字符串。
        /// </summary>
        internal static string AutomaticOnOffACSwitch {
            get {
                return ResourceManager.GetString("AutomaticOnOffACSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换后自动关闭面板 的本地化字符串。
        /// </summary>
        internal static string HideFlyoutAfterSchemaChangeSwitch {
            get {
                return ResourceManager.GetString("HideFlyoutAfterSchemaChangeSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Icon made by Cursor creative 的本地化字符串。
        /// </summary>
        internal static string IconLicence {
            get {
                return ResourceManager.GetString("IconLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.flaticon.com/authors/cursor-creative 的本地化字符串。
        /// </summary>
        internal static string IconLicenceURL {
            get {
                return ResourceManager.GetString("IconLicenceURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拔出电源时切换到 的本地化字符串。
        /// </summary>
        internal static string SchemaToSwitchOffAc {
            get {
                return ResourceManager.GetString("SchemaToSwitchOffAc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插上电源时切换到 的本地化字符串。
        /// </summary>
        internal static string SchemaToSwitchOnAc {
            get {
                return ResourceManager.GetString("SchemaToSwitchOnAc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅显示默认电源模式 的本地化字符串。
        /// </summary>
        internal static string ShowOnlyDefaultSchemas {
            get {
                return ResourceManager.GetString("ShowOnlyDefaultSchemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开机自启 的本地化字符串。
        /// </summary>
        internal static string Startup {
            get {
                return ResourceManager.GetString("Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快捷键呼出面板 的本地化字符串。
        /// </summary>
        internal static string ToggleOnShowrtcutSwitch {
            get {
                return ResourceManager.GetString("ToggleOnShowrtcutSwitch", resourceCulture);
            }
        }
    }
}
